"""add Service model

Revision ID: 4710684b81e1
Revises: f65d7b72549a
Create Date: 2023-01-14 14:06:41.616900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4710684b81e1"
down_revision = "f65d7b72549a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service", schema=None) as batch_op:
        batch_op.alter_column("description", existing_type=sa.VARCHAR(length=1000), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service", schema=None) as batch_op:
        batch_op.alter_column("description", existing_type=sa.VARCHAR(length=1000), nullable=False)

    # ### end Alembic commands ###
