"""update service model

Revision ID: 5926df22a7cf
Revises: 4710684b81e1
Create Date: 2023-01-15 17:27:28.397519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5926df22a7cf"
down_revision = "4710684b81e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service", schema=None) as batch_op:
        batch_op.alter_column("description", existing_type=sa.VARCHAR(length=1000), nullable=False)
        batch_op.alter_column("duration", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service", schema=None) as batch_op:
        batch_op.alter_column("duration", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("description", existing_type=sa.VARCHAR(length=1000), nullable=True)

    # ### end Alembic commands ###
